openapi: 3.0.0
info:
  title: FleetScore API
  version: 1.0.0

servers:
  - url: /api
    description: API server

# list of available tags for API endpoints
tags:
  - name: about
    description: Information about Fleetscore
  - name: points
    description: Points management
  - name: accounts
    description: User account management
  - name: catalog
    description: Product catalog management
  - name: orders
    description: Order processing and history
  - name: notifications
    description: Notification management
  - name: applications
    description: Driver application management
  - name: reports
    description: Report generation and retrieval
  - name: views
    description: View pages as other user roles
  - name: audit logs
    description: Audit log retrieval and management
  - name: security
    description: Security-related endpoints
  - name: sponsor companies
    description: Sponsor company management
  - name: store
    description: External store product search and retrieval

paths:

  ### about ###

  /about:
    $ref: './paths/about.yaml#/about'

  ### store ###

  /admin/store/search:
    $ref: './paths/admin/store.yaml#/productSearch'

  /admin/store/products/{productId}:
    $ref: './paths/admin/store.yaml#/productsById'

  ### catalogs - admin ###

  /admin/catalogs:
    $ref: './paths/admin/catalogs.yaml#/catalogs'

  /admin/catalogs/{catalogId}:
    $ref: './paths/admin/catalogs.yaml#/catalogsById'

  /admin/catalogs/{catalogId}/items:
    $ref: './paths/admin/catalogs.yaml#/catalogItems'

  /admin/catalogs/{catalogId}/items/{itemId}:
    $ref: './paths/admin/catalogs.yaml#/catalogItemsById'

  /admin/catalogs/{catalogId}/items/{itemId}/reviews:
    $ref: './paths/admin/catalogs.yaml#/catalogItemReviews'

  /admin/catalogs/{catalogId}/items/{itemId}/reviews/{reviewId}:
    $ref: './paths/admin/catalogs.yaml#/catalogItemReviewsById'

  ### users - admin ###

  /admin/users:
    $ref: './paths/admin/users.yaml#/users'

  /admin/users/{id}:
    $ref: './paths/admin/users.yaml#/usersById'

  /admin/users/{id}/points:
    $ref: './paths/admin/users.yaml#/userPoints'

  /admin/users/{id}/points/{transactionId}:
    $ref: './paths/admin/users.yaml#/userPointsTransaction'

  /admin/assume-driver/{targetUserId}:
    $ref: './paths/admin/users.yaml#/assumeDriver'

  /admin/assume-sponsor/{targetUserId}:
    $ref: './paths/admin/users.yaml#/assumeSponsor'

  /auth/assumption-exit:
    $ref: './paths/auth.yaml#/assumptionExit'

  ### catalogs - driver ###

  /driver/{userId}/catalogs:
    $ref: './paths/driver/catalogs.yaml#/catalogs'

  /driver/{userId}/catalogs/{catalogId}:
    $ref: './paths/driver/catalogs.yaml#/catalogsById'

  /driver/{userId}/catalogs/{catalogId}/items/{itemId}:
    $ref: './paths/driver/catalogs.yaml#/catalogItemById'

  /driver/{userId}/orders:
    $ref: './paths/driver/orders.yaml#/orders'

  /driver/{userId}/orders/{orderId}:
    $ref: './paths/driver/orders.yaml#/ordersById'

  /sponsor/{userId}/catalogs:
    $ref: './paths/sponsor/catalogs.yaml#/catalogs'

  /sponsor/{userId}/catalogs/{catalogId}:
    $ref: './paths/sponsor/catalogs.yaml#/catalogsById'

  /sponsor/{userId}/catalogs/{catalogId}/items:
    $ref: './paths/sponsor/catalogs.yaml#/catalogItems'

  /sponsor/{userId}/catalogs/{catalogId}/items/{itemId}:
    $ref: './paths/sponsor/catalogs.yaml#/catalogItemsById'

  /sponsors/{userId}/assume-driver/{driverId}:
    $ref: './paths/sponsor/catalogs.yaml#/assumeDriver'

  ### reports - admin ###

  /admin/reports/driver-applications:
    $ref: './paths/admin/reports.yaml#/driverApplications'

  ### reports - sponsor ###
  
  /sponsor/{userId}/reports/driver-applications:
    $ref: './paths/sponsor/reports.yaml#/driverApplications'

  /sponsor/{userId}/reports/generated:
    $ref: './paths/sponsor/reports.yaml#/generated'

  /sponsor/{userId}/reports/generated/{reportId}/download:
    $ref: './paths/sponsor/reports.yaml#/generatedDownload'

components:
# placeholder security schema for linting purposes
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionId
      description: Session-based authentication using cookies

security:
  - cookieAuth: []